### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AhmetDS** [BGMP/firefox-revert-proton#2]
Icons should be more grey, needs a separator between the new tab button and tab if not active and there are no lines on tabs(outline I think what you call them) // Based on light theme submitted on old repository

Edit: I disabled browser.proton.enabled everything solved except icons

**Comment by BGMP** [comment]
Note that Firefox will eventually remove `browser.proton.enabled` if I'm not mistaken

**Comment by AhmetDS** [comment]
> 
> 
> Note that Firefox will eventually remove `browser.proton.enabled` if I'm not mistaken

I think they already removed it, couldn't use version 90.1 because of the issues above. I downgraded to 88.

**Comment by BGMP** [comment]
> 
> I think they already removed it, couldn't use version 90.1 because of the issues above. I downgraded to 88.

hm, the idea of this project is so that you don't have to downgrade in order to get older looks. Have you tried implementing your suggestion at all?

**Comment by AhmetDS** [comment]
> 
> 
> > I think they already removed it, couldn't use version 90.1 because of the issues above. I downgraded to 88.
> 
> hm, the idea of this project is so that you don't have to downgrade in order to get older looks. Have you tried implementing your suggestion at all?

Yes, I did try and separators, outline, even compact mode(not so much different) was proton style.
